<?php
// This script and data application were generated by AppGini 5.70
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/Ma.php");
	include("$currDir/Ma_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('Ma');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "Ma";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`Ma`.`id`" => "id",
		"`Ma`.`Type`" => "Type",
		"`Ma`.`Name`" => "Name",
		"if(`Ma`.`Date_Of_Receipt`,date_format(`Ma`.`Date_Of_Receipt`,'%d/%m/%Y'),'')" => "Date_Of_Receipt",
		"if(`Ma`.`Date_Published`,date_format(`Ma`.`Date_Published`,'%d/%m/%Y'),'')" => "Date_Published",
		"`Ma`.`Pages`" => "Pages",
		"`Ma`.`Price`" => "Price",
		"`Ma`.`Publisher`" => "Publisher"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`Ma`.`id`',
		2 => 2,
		3 => 3,
		4 => '`Ma`.`Date_Of_Receipt`',
		5 => '`Ma`.`Date_Published`',
		6 => '`Ma`.`Pages`',
		7 => '`Ma`.`Price`',
		8 => 8
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`Ma`.`id`" => "id",
		"`Ma`.`Type`" => "Mã Hợp Đồng",
		"`Ma`.`Name`" => "Danh Mục Thuê",
		"if(`Ma`.`Date_Of_Receipt`,date_format(`Ma`.`Date_Of_Receipt`,'%d/%m/%Y'),'')" => "Ngày Ký Hợp Đồng",
		"if(`Ma`.`Date_Published`,date_format(`Ma`.`Date_Published`,'%d/%m/%Y'),'')" => "Ngày Hết Hạn",
		"`Ma`.`Pages`" => "Khách Hàng",
		"`Ma`.`Price`" => "Chi Phí ",
		"`Ma`.`Publisher`" => "Ghi Chú"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`Ma`.`id`" => "ID",
		"`Ma`.`Type`" => " Mã Hợp Đồng",
		"`Ma`.`Name`" => "Danh Mục Thuê",
		"`Ma`.`Date_Of_Receipt`" => "Ngày Ký Hợp Đồng",
		"`Ma`.`Date_Published`" => "Ngày Hết Hạn",
		"`Ma`.`Pages`" => "Khách Hàng",
		"`Ma`.`Price`" => "Chi Phí",
		"`Ma`.`Publisher`" => "Ghi Chú"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`Ma`.`id`" => "id",
		"`Ma`.`Type`" => "Mã Hợp Đồng",
		"`Ma`.`Name`" => "Danh Mục Thuê",
		"if(`Ma`.`Date_Of_Receipt`,date_format(`Ma`.`Date_Of_Receipt`,'%d/%m/%Y'),'')" => "Ngày Ký Hợp Đồng",
		"if(`Ma`.`Date_Published`,date_format(`Ma`.`Date_Published`,'%d/%m/%Y'),'')" => "Ngày Hết Hạn",
		"`Ma`.`Pages`" => "Khách Hàng",
		"`Ma`.`Price`" => "Chi Phí ",
		"`Ma`.`Publisher`" => "Ghi Chú"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom = "`Ma` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "Ma_view.php";
	$x->RedirectAfterInsert = "Ma_view.php?SelectedID=#ID#";
	$x->TableTitle = "Danh Sách Hợp Đồng";
	$x->TableIcon = "resources/table_icons/blogs.png";
	$x->PrimaryKey = "`Ma`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 80, 150);
	$x->ColCaption = array("Mã Hợp Đồng", "Danh Mục Thuê", "Ngày Ký Hợp Đồng", " Ngày Hết Hạn", "Khách Hàng", "Chi Phí ", "Ghi Chú");
	$x->ColFieldName = array('Type', 'Name', 'Date_Of_Receipt', 'Date_Published', 'Pages', 'Price', 'Publisher');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8);

	// template paths below are based on the app main directory
	$x->Template = 'templates/Ma_templateTV.html';
	$x->SelectedTemplate = 'templates/Ma_templateTVS.html';
	$x->TemplateDV = 'templates/Ma_templateDV.html';
	$x->TemplateDVP = 'templates/Ma_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `Ma`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='Ma' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `Ma`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='Ma' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`Ma`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: Magazines_init
	$render=TRUE;
	if(function_exists('Ma_init')){
		$args=array();
		$render=Ma_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Magazines_header
	$headerCode='';
	if(function_exists('Ma_header')){
		$args=array();
		$headerCode=Ma_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: Magazines_footer
	$footerCode='';
	if(function_exists('Ma_footer')){
		$args=array();
		$footerCode=Ma_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>