<?php
// This script and data application were generated by AppGini 5.70
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/NewsPaper.php");
	include("$currDir/NewsPaper_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('NewsPaper');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "NewsPaper";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`NewsPaper`.`id`" => "id",
		"`NewsPaper`.`Language`" => "Language",
		"`NewsPaper`.`Name`" => "Name",
		"if(`NewsPaper`.`Date_Of_Receipt`,date_format(`NewsPaper`.`Date_Of_Receipt`,'%d/%m/%Y'),'')" => "Date_Of_Receipt",
		"if(`NewsPaper`.`Date_Published`,date_format(`NewsPaper`.`Date_Published`,'%d/%m/%Y'),'')" => "Date_Published",
		"`NewsPaper`.`Pages`" => "Pages",
		"`NewsPaper`.`Price`" => "Price",
		"`NewsPaper`.`Type`" => "Type",
		"`NewsPaper`.`Publisher`" => "Publisher",
		"`NewsPaper`.`Typess`" => "Typess",
		"`NewsPaper`.`Pu`" => "Pu"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`NewsPaper`.`id`',
		2 => 2,
		3 => 3,
		4 => '`NewsPaper`.`Date_Of_Receipt`',
		5 => '`NewsPaper`.`Date_Published`',
		6 => '`NewsPaper`.`Pages`',
		7 => '`NewsPaper`.`Price`',
		8 => '`NewsPaper`.`Type`',
		9 => 9,
		10 =>10,
		11 => 11
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`NewsPaper`.`id`" => "id",
		"`NewsPaper`.`Language`" => "Mã Nhân Viên",
		"`NewsPaper`.`Name`" => "Tên Nhân Viên",
		"if(`NewsPaper`.`Date_Of_Receipt`,date_format(`NewsPaper`.`Date_Of_Receipt`,'%d/%m/%Y'),'')" => "Năm Sinh",
		"if(`NewsPaper`.`Date_Published`,date_format(`NewsPaper`.`Date_Published`,'%d/%m/%Y'),'')" => "Ngày Nhận Việc",
		"`NewsPaper`.`Pages`" => "Chức Vụ",
		"`NewsPaper`.`Price`" => "Mức Lương",
		"`NewsPaper`.`Type`" => "Hợp Đồng Làm Việc",
		"`NewsPaper`.`Publisher`" => "Quê Quán",
		"`NewsPaper`.`Typess`" => "Giới Tính",
		"`NewsPaper`.`Pu`" => "Số Điện Thoại"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`NewsPaper`.`id`" => "ID",
		"`NewsPaper`.`Language`" => "Mã Nhân Viên",
		"`NewsPaper`.`Name`" => "Tên Nhân Viên",
		"`NewsPaper`.`Date_Of_Receipt`" => "Năm Sinh",
		"`NewsPaper`.`Date_Published`" => "Ngày Nhận Việc",
		"`NewsPaper`.`Pages`" => "Chức Vụ",
		"`NewsPaper`.`Price`" => "Mức Lương",
		"`NewsPaper`.`Type`" => "Hợp Đồng Làm Việc",
		"`NewsPaper`.`Publisher`" => "Quê Quán",
		"`NewsPaper`.`Typess`" => "Giới Tính",
		"`NewsPaper`.`Pu`" => "Số Điện Thoại"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`NewsPaper`.`id`" => "id",
		"`NewsPaper`.`Language`" => "Mã Nhân Viên",
		"`NewsPaper`.`Name`" => "Tên Nhân Viên",
		"if(`NewsPaper`.`Date_Of_Receipt`,date_format(`NewsPaper`.`Date_Of_Receipt`,'%d/%m/%Y'),'')" => "Năm Sinh",
		"if(`NewsPaper`.`Date_Published`,date_format(`NewsPaper`.`Date_Published`,'%d/%m/%Y'),'')" => "Ngày Nhận Việc",
		"`NewsPaper`.`Pages`" => "Chức Vụ",
		"`NewsPaper`.`Price`" => "Mức Lương",
		"`NewsPaper`.`Type`" => "Hợp Đồng Làm Việc",
		"`NewsPaper`.`Publisher`" => "Quê Quán",
		"`NewsPaper`.`Typess`" => "Giới Tính",
		"`NewsPaper`.`Pu`" => "Số Điện Thoại"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom = "`NewsPaper` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "NewsPaper_view.php";
	$x->RedirectAfterInsert = "NewsPaper_view.php?SelectedID=#ID#";
	$x->TableTitle = "Danh Sách Nhân Viên";
	$x->TableIcon = "resources/table_icons/books.png";
	$x->PrimaryKey = "`NewsPaper`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 80, 150, 150,150,150);
	$x->ColCaption = array("Mã Nhân Viên", "Tên Nhân Viên", "Năm Sinh", "Ngày Nhận Việc", "Chức Vụ", "Mức Lương", "Hợp Đồng Làm Việc", "Quê Quán","Giới Tính", "Số Điện Thoại");
	$x->ColFieldName = array('Language', 'Name', 'Date_Of_Receipt', 'Date_Published', 'Pages', 'Price', 'Type', 'Publisher','Typess','Pu');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8, 9,10,11);

	// template paths below are based on the app main directory
	$x->Template = 'templates/NewsPaper_templateTV.html';
	$x->SelectedTemplate = 'templates/NewsPaper_templateTVS.html';
	$x->TemplateDV = 'templates/NewsPaper_templateDV.html';
	$x->TemplateDVP = 'templates/NewsPaper_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `NewsPaper`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='NewsPaper' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `NewsPaper`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='NewsPaper' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`NewsPaper`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: NewsPapers_init
	$render=TRUE;
	if(function_exists('NewsPaper_init')){
		$args=array();
		$render=NewsPaper_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: NewsPapers_header
	$headerCode='';
	if(function_exists('NewsPaper_header')){
		$args=array();
		$headerCode=NewsPaper_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: NewsPapers_footer
	$footerCode='';
	if(function_exists('NewsPaper_footer')){
		$args=array();
		$footerCode=NewsPaper_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>