<?php
// This script and data application were generated by AppGini 5.70
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/Typ.php");
	include("$currDir/Typ_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('Typ');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "Typ";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`Typ`.`id`" => "id",
		"`Typ`.`Na`" => "Na",
		"`Typ`.`t`" => "t",
		"`Typ`.`C`" => "C",
		"`Typ`.`D`" => "D",
		"`Typ`.`I`" => "I",
		"`Typ`.`e`" => "e"

	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`Typ`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 =>'`Typ`.`e`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`Typ`.`id`" => "STT",
		"`Typ`.`Na`" => "Thiết Bị Đã Sửa Chữa",
		"`Typ`.`t`" => "Số Lượng",
		"`Typ`.`C`" => "Ngày Sửa Chữa",
		"`Typ`.`D`" => "Công Ty Sửa Chữa",
		"`Typ`.`I`" => "Chi Phí Sửa Chữa",
		"`Typ`.`e`" => "Ghi Chú"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`Typ`.`id`" => "STT",
		"`Typ`.`Na`" => "Thiết Bị Đã Sửa Chữa",
		"`Typ`.`t`" => "Số Lượng",
		"`Typ`.`C`" => "Ngày Sửa Chữa",
		"`Typ`.`D`" => "Công Ty Sửa Chữa",
		"`Typ`.`I`" => "Chi Phí Sửa Chữa",
		"`Typ`.`e`" => "Ghi Chú"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`Typ`.`id`" => "STT",
		"`Typ`.`Na`" => "Thiết Bị Đã Sửa Chữa",
		"`Typ`.`t`" => "Số Lượng",
		"`Typ`.`C`" => "Ngày Sửa Chữa",
		"`Typ`.`D`" => "Công Ty Sửa Chữa",
		"`Typ`.`I`" => "Chi Phí Sửa Chữa",
		"`Typ`.`e`" => "Ghi Chú"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom = "`Typ` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "Typ_view.php";
	$x->RedirectAfterInsert = "Typ_view.php?SelectedID=#ID#";
	$x->TableTitle = "Chi Phí Sửa Chữa";
	$x->TableIcon = "resources/table_icons/blogs.png";
	$x->PrimaryKey = "`Typ`.`id`";

	$x->ColWidth   = array(  150,150,150,150,150,150);
	$x->ColCaption = array("Thiết Bị Đã Sửa Chữa","Số Lượng","Ngày Sữa Chữa","Công Ty Sữa Chữa","Chi Phí Sữa Chữa","Ghi Chú");
	$x->ColFieldName = array('Na','t','C','D','I','e');
	$x->ColNumber  = array(2,3,4,5,6,7);

	// template paths below are based on the app main directory
	$x->Template = 'templates/Typ_templateTV.html';
	$x->SelectedTemplate = 'templates/Typ_templateTVS.html';
	$x->TemplateDV = 'templates/Typ_templateDV.html';
	$x->TemplateDVP = 'templates/Typ_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `Typ`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='Typ' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `Typ`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='Typ' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`Typ`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: Types_init
	$render=TRUE;
	if(function_exists('Typ_init')){
		$args=array();
		$render=Typ_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Types_header
	$headerCode='';
	if(function_exists('Typ_header')){
		$args=array();
		$headerCode=Typ_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: Types_footer
	$footerCode='';
	if(function_exists('Typ_footer')){
		$args=array();
		$footerCode=Typ_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>