<?php
// This script and data application were generated by AppGini 5.70
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/Type.php");
	include("$currDir/Type_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('Type');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "Type";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`Type`.`id`" => "id",
		"`Type`.`Name`" => "Name",
		"`Type`.`tt`" => "tt",
		"`Type`.`CC`" => "CC",
		"`Type`.`ID_N`" => "ID_N"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`Type`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => '`Type`.`ID_N`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`Type`.`id`" => "id",
		"`Type`.`Name`" => "Tên Thiết Bị",
		"`Type`.`tt`" => "Thông Tin Bảo Hành",
		"`Type`.`CC`" => "Tình Trạng Hư Hỏng",
		"`Type`.`ID_N`" => "Ghi Chú"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`Type`.`id`" => "ID",
			"`Type`.`Name`" => "Tên Thiết Bị",
		"`Type`.`tt`" => "Thông Tin Bảo Hành",
		"`Type`.`CC`" => "Tình Trạng Hư Hỏng",
		"`Type`.`ID_N`" => "Ghi Chú"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`Type`.`id`" => "id",
			"`Type`.`Name`" => "Tên Thiết Bị",
		"`Type`.`tt`" => "Thông Tin Bảo Hành",
		"`Type`.`CC`" => "Tình Trạng Hư Hỏng",
		"`Type`.`ID_N`" => "Ghi Chú"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom = "`Type` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "Type_view.php";
	$x->RedirectAfterInsert = "Type_view.php?SelectedID=#ID#";
	$x->TableTitle = "Thiết Bị Hư Hỏng";
	$x->TableIcon = "resources/table_icons/blogs.png";
	$x->PrimaryKey = "`Type`.`id`";

	$x->ColWidth   = array(  150,150,150,150);
	$x->ColCaption = array("Tên Thiết Bị","Thông Tin Bảo Hành","Tình Trạng Hư Hỏng","Ghi Chú");
	$x->ColFieldName = array('Name','tt','CC','ID_N');
	$x->ColNumber  = array(2,3,4,5);

	// template paths below are based on the app main directory
	$x->Template = 'templates/Type_templateTV.html';
	$x->SelectedTemplate = 'templates/Type_templateTVS.html';
	$x->TemplateDV = 'templates/Type_templateDV.html';
	$x->TemplateDVP = 'templates/Type_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `Type`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='Type' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `Type`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='Type' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`Type`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: Types_init
	$render=TRUE;
	if(function_exists('Type_init')){
		$args=array();
		$render=Type_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Types_header
	$headerCode='';
	if(function_exists('Type_header')){
		$args=array();
		$headerCode=Type_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: Types_footer
	$footerCode='';
	if(function_exists('Type_footer')){
		$args=array();
		$footerCode=Type_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>